# Generated by Django 5.1.5 on 2025-01-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="identifier",
            new_name="matric_number",
        ),
    ]
