# Generated by Django 5.1.5 on 2025-01-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
    ]
