# Generated by Django 5.1.5 on 2025-02-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_assignmentsubmission_delete_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_text", models.TextField()),
                ("fingerprints", models.JSONField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="processing", max_length=20)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.assignmentsubmission",
                    ),
                ),
            ],
        ),
    ]
