# Generated by Django 5.1.5 on 2025-02-11 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_processeddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("matching_segments", models.JSONField()),
                ("compared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_results",
                        to="api.assignmentsubmission",
                    ),
                ),
                (
                    "submission2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compared_results",
                        to="api.assignmentsubmission",
                    ),
                ),
            ],
        ),
    ]
